---
title: "Collaboration"
author: "Ranae Dietzel and Andee Kaplan"
date: "September 2, 2016"
output: html_document
---

##Prompt
You study free-living diaztrophs, microbes with can fix nitrogen without a symbiotic relationship with a plant. While at a conference, you meet another scientist who has similar interests, but lives in Ukraine. As you talk, you realize that the soils and agriculture in Iowa and Ukraine have many similarities. Then you find out that abundance of the *nif* gene that she measured in the soil of her cornfield is 10 times greater than what you have ever measured in Iowa. You both get excited and strike up a collaboration to try and study the effect of this difference on yield given an identical fertilizer rate.  

As the project progresses, you realize that there are many factors you can control to make the Iowan and Ukrainian field sites similar, but there are many other variables you cannot control and you will have to measure and try to account for their effect through modeling. Each of you quickly recruit soil scientists, crop scientists, meteorologists, and statisticians. You immediatley recognize the need for a data dictionary and start to work with your co-PI to craft one. 

Luckily, your co-PI uses both R Markdown and GitHub.  Also, there is enough of a time difference so that you are never working on the same file at the same time. You start by identifiying the following important measured variables: biomass yield, harvest index (grain/biomass), number of seeds per hectare, precipitation, radiation, maximum daily temperature, soil nitrate, *nif* abundance, nitrogenase activity.  

##Instructions  
Work with a partner to create a data dictionary as if one of you is the PI in Ukraine. The list above is by no means complete, when the file is pushed to you, add a variable or other piece of information and push it back to your collaborator.  

You may want to copy and paste this to make a table in R markdown:  


```{r kable, echo=FALSE}
ourtable <- data.frame(name=c("gyield", "precip", "var3", "var4"),
                  plot_name=c("Grain Yield", "Precipitation", "Variable 3", "Variable 4"),
                  group=c("crops", "met", "other", "other"),
                  description=c("How much grain was produced", "How much it rained during the growing season",
                                "More things about this",
                                "And description of that"),
                  stringsAsFactors=FALSE)
kable(ourtable)
```


####To start  
1) Fork the "lab" repo from our organization's GitHub page.  
2) Create a new repo within the lab repo and add your partner as a collaborator  
3) Make a brand new file within this repo and begin to build the dictionary.  
4) When you are ready, commit your changes and push them to the repo.  
5) The partner can then pull the file, incorporate their changes, and push back. 

