###Dates, dplyr, tidyr

#This dataset was generated by running a cropping systems model (APSIM) with daily weather
 #predictions generated by a climate model. It represents 50 years of a corn-soybean rotation
 #in central Iowa, USA. 

library(tidyverse)

data_dictionary<-data.frame(variable = c("date", "rain", "soil_water", "soil_temp", "soy_yield", "maize_yield", "nh4",
                              "no3", "n_fixation", "n_leaching", "soil_n_min", "n_uptake"), 
                            unit = c("dd/mm/yyyy", "mm", "mm", "degC", "kg/ha", "kg/ha", "kg/mg",
                              "kg/mg", "kg", "kg", "kg", "kg"), 
                            definition = c("date", "mm of rain", 
                                            "amount of water in the soil to 15 cm", 
                                           "soil temp at 15 cm", "soybean grain yield",
                                           "maize grain yield", "ammonium concentration in soil", 
                                           "nitrate concentration in soil", "kg of nitrogen fixed", 
                                           "kg of nitrogen leached", 
                                            "kg of soil nitrogen produced by mineralization", 
                                            "kg of nitrogen taken up by the plant" ))
future<-read_csv("future.csv", na = "?")  

#Use `qplot(x, y, data=future)` to explore a few simple relationships 
#Try `qplot(date, y, data=future) (may take a minute to print)

#Change the dates to the proper format and plot again
#Add a year column  
#Add a month column  
#Add day of year column 

#Sum rainfall ammounts for each year and plot across years
#Find the average soil temp for each year and plot across years
#Averaged across all years, which month has the most rain?

#Plot the change in soil temperature over one year.  
#Plot the change in soil temperature over all years. 

#Make a column for total inorganic nitrogen (nh4 + no3)
#Does soil inorganic nitrogen change over 50 years?

#How many days are there between recordings of maize yield?

#Which takes up more nitrogen, soybean or maize 
 #(you may want to use tidyr for this, but don't have to)?



  
